"""Source-class sets for Python Ironbug OpenStudio writer planning."""

from __future__ import annotations

from garden.ironbug_console.openstudio_source_classes import (
    GENERIC_AIR_LOOP_COMPONENT_SOURCE_CLASSES as _GENERIC_AIR_LOOP_COMPONENT_SOURCE_CLASSES,
    GENERIC_OPENSTUDIO_SOURCE_CLASSES as _GENERIC_OPENSTUDIO_SOURCE_CLASSES,
    GENERIC_PLANT_COMPONENT_SOURCE_CLASSES as _GENERIC_PLANT_COMPONENT_SOURCE_CLASSES,
    NOOP_CONTAINER_SOURCE_CLASSES as _NOOP_CONTAINER_SOURCE_CLASSES,
    SETPOINT_MANAGER_SOURCE_CLASSES as _SETPOINT_MANAGER_SOURCE_CLASSES,
    SPECIAL_AIR_LOOP_COMPONENT_SOURCE_CLASSES as _SPECIAL_AIR_LOOP_COMPONENT_SOURCE_CLASSES,
    SPECIAL_OPENSTUDIO_SOURCE_CLASSES as _SPECIAL_OPENSTUDIO_SOURCE_CLASSES,
    SPECIAL_PLANT_COMPONENT_SOURCE_CLASSES as _SPECIAL_PLANT_COMPONENT_SOURCE_CLASSES,
)


_SUPPORTED_SOURCE_CLASSES = frozenset(
    {
        *_NOOP_CONTAINER_SOURCE_CLASSES,
        *_SPECIAL_OPENSTUDIO_SOURCE_CLASSES,
        *_GENERIC_OPENSTUDIO_SOURCE_CLASSES,
        *_SETPOINT_MANAGER_SOURCE_CLASSES,
        "IB_CoilCoolingDXSingleSpeed",
        "IB_CoilCoolingWater",
        "IB_CoilHeatingDXSingleSpeed",
        "IB_CoilHeatingElectric",
        "IB_CoilHeatingWater",
        "IB_CoilCoolingDXVariableRefrigerantFlow",
        "IB_CoilHeatingDXVariableRefrigerantFlow",
        "IB_AirLoopBranches",
        "IB_AirLoopHVAC",
        "IB_AirLoopHVACUnitarySystem",
        "IB_CoilHeatingWaterBaseboardRadiant",
        "IB_ControllerMechanicalVentilation",
        "IB_ControllerOutdoorAir",
        "IB_OutdoorAirSystem",
        "IB_AirTerminalSingleDuctConstantVolumeNoReheat",
        "IB_AirTerminalSingleDuctConstantVolumeReheat",
        "IB_AirTerminalSingleDuctConstantVolumeCooledBeam",
        "IB_AirTerminalSingleDuctConstantVolumeFourPipeBeam",
        "IB_AirTerminalSingleDuctConstantVolumeFourPipeInduction",
        "IB_AirTerminalSingleDuctInletSideMixer",
        "IB_AirTerminalSingleDuctParallelPIUReheat",
        "IB_AirTerminalSingleDuctSeriesPIUReheat",
        "IB_AirTerminalSingleDuctVAVHeatAndCoolNoReheat",
        "IB_AirTerminalSingleDuctVAVHeatAndCoolReheat",
        "IB_AirTerminalSingleDuctVAVNoReheat",
        "IB_AirTerminalSingleDuctVAVReheat",
        "IB_BoilerHotWater",
        "IB_ChillerElectricEIR",
        "IB_CoolingTowerVariableSpeed",
        "IB_CurveBicubic",
        "IB_CurveBiquadratic",
        "IB_CurveCubic",
        "IB_CurveExponent",
        "IB_CurveFanPressureRise",
        "IB_CurveLinear",
        "IB_CurveQuadratic",
        "IB_CurveQuartic",
        "IB_CurveSigmoid",
        "IB_CurveTriquadratic",
        "IB_DistrictCooling",
        "IB_DistrictHeatingWater",
        "IB_HeatExchangerFluidToFluid",
        "IB_AirConditionerVariableRefrigerantFlow",
        "IB_CoilCoolingCooledBeam",
        "IB_CoilCoolingFourPipeBeam",
        "IB_CoilHeatingFourPipeBeam",
        "IB_FanConstantVolume",
        "IB_FanVariableVolume",
        "IB_FanOnOff",
        "IB_PlantLoop",
        "IB_PlantLoopBranches",
        "IB_PumpConstantSpeed",
        "IB_PumpVariableSpeed",
        "IB_ScheduleDay",
        "IB_ScheduleFile",
        "IB_ScheduleRule",
        "IB_ScheduleRuleset",
        "IB_ScheduleTypeLimits",
        "IB_SizingPlant",
        "IB_SizingSystem",
        "IB_SizingZone",
        "IB_ThermalZone",
        "IB_OutputVariable",
        "IB_ZoneHVACFourPipeFanCoil",
        "IB_ZoneHVACBaseboardRadiantConvectiveWater",
        "IB_ZoneHVACPackagedTerminalAirConditioner",
        "IB_ZoneHVACPackagedTerminalHeatPump",
        "IB_ZoneHVACTerminalUnitVariableRefrigerantFlow",
        "IB_ZoneHVACUnitHeater",
        "IB_ZoneHVACUnitVentilator_CoolingHeating",
        "IB_ZoneHVACUnitVentilator_CoolingOnly",
        "IB_ZoneHVACUnitVentilator_HeatingOnly",
    }
)

_TERMINAL_COMPONENT_SOURCE_CLASSES = frozenset(
    {
        *_SPECIAL_AIR_LOOP_COMPONENT_SOURCE_CLASSES,
        *_SPECIAL_PLANT_COMPONENT_SOURCE_CLASSES,
        *_GENERIC_AIR_LOOP_COMPONENT_SOURCE_CLASSES,
        *_GENERIC_PLANT_COMPONENT_SOURCE_CLASSES,
        *_SETPOINT_MANAGER_SOURCE_CLASSES,
        "IB_CoilCoolingDXSingleSpeed",
        "IB_CoilCoolingDXVariableRefrigerantFlow",
        "IB_CoilCoolingWater",
        "IB_CoilHeatingDXSingleSpeed",
        "IB_CoilHeatingDXVariableRefrigerantFlow",
        "IB_CoilHeatingElectric",
        "IB_CoilHeatingWater",
        "IB_CoilHeatingWaterBaseboardRadiant",
        "IB_ControllerWaterCoil",
        "IB_AirLoopBranches",
        "IB_AirLoopHVACUnitarySystem",
        "IB_AirTerminalSingleDuctConstantVolumeNoReheat",
        "IB_AirTerminalSingleDuctConstantVolumeReheat",
        "IB_AirTerminalSingleDuctConstantVolumeCooledBeam",
        "IB_AirTerminalSingleDuctConstantVolumeFourPipeBeam",
        "IB_AirTerminalSingleDuctConstantVolumeFourPipeInduction",
        "IB_AirTerminalSingleDuctInletSideMixer",
        "IB_AirTerminalSingleDuctParallelPIUReheat",
        "IB_AirTerminalSingleDuctSeriesPIUReheat",
        "IB_AirTerminalSingleDuctVAVHeatAndCoolNoReheat",
        "IB_AirTerminalSingleDuctVAVHeatAndCoolReheat",
        "IB_AirTerminalSingleDuctVAVNoReheat",
        "IB_AirTerminalSingleDuctVAVReheat",
        "IB_BoilerHotWater",
        "IB_ChillerElectricEIR",
        "IB_CoilCoolingCooledBeam",
        "IB_ControllerMechanicalVentilation",
        "IB_ControllerOutdoorAir",
        "IB_CoolingTowerVariableSpeed",
        "IB_DistrictCooling",
        "IB_DistrictHeatingWater",
        "IB_HeatExchangerFluidToFluid",
        "IB_CoilCoolingFourPipeBeam",
        "IB_CoilHeatingFourPipeBeam",
        "IB_FanConstantVolume",
        "IB_FanVariableVolume",
        "IB_FanOnOff",
        "IB_OutdoorAirSystem",
        "IB_PlantLoopBranches",
        "IB_PumpConstantSpeed",
        "IB_PumpVariableSpeed",
        "IB_ZoneHVACTerminalUnitVariableRefrigerantFlow",
    }
)
