"""Explicit writer-family source-class maps for Python Console writers."""

from __future__ import annotations


FIRST_WRITER_FAMILY_NAMES = (
    "thermal_zone",
    "schedules",
    "curves",
    "sizing",
    "output_requests",
)

_EXPLICIT_IMPLEMENTED_SOURCE_CLASSES: dict[str, str] = {
    "IB_ThermalZone": "thermal_zone",
    "IB_ScheduleDay": "schedules",
    "IB_ScheduleFile": "schedules",
    "IB_ScheduleRule": "schedules",
    "IB_ScheduleRuleset": "schedules",
    "IB_ScheduleTypeLimits": "schedules",
    "IB_CurveBicubic": "curves",
    "IB_CurveBiquadratic": "curves",
    "IB_CurveCubic": "curves",
    "IB_CurveExponent": "curves",
    "IB_CurveFanPressureRise": "curves",
    "IB_CurveLinear": "curves",
    "IB_CurveQuadratic": "curves",
    "IB_CurveQuartic": "curves",
    "IB_CurveSigmoid": "curves",
    "IB_CurveTriquadratic": "curves",
    "IB_SizingPlant": "sizing",
    "IB_SizingSystem": "sizing",
    "IB_SizingZone": "sizing",
    "IB_OutputVariable": "output_requests",
    "IB_AirLoopBranches": "air_loop_components",
    "IB_AirLoopHVAC": "air_loops",
    "IB_AirLoopHVACUnitarySystem": "air_loop_unitary",
    "IB_ControllerMechanicalVentilation": "air_loop_components",
    "IB_ControllerOutdoorAir": "air_loop_components",
    "IB_OutdoorAirSystem": "air_loop_components",
    "IB_AirTerminalSingleDuctConstantVolumeNoReheat": "air_terminals",
    "IB_AirTerminalSingleDuctConstantVolumeReheat": "air_terminals",
    "IB_AirTerminalSingleDuctConstantVolumeCooledBeam": "air_terminals",
    "IB_AirTerminalSingleDuctConstantVolumeFourPipeBeam": "air_terminals",
    "IB_AirTerminalSingleDuctConstantVolumeFourPipeInduction": "air_terminals",
    "IB_AirTerminalSingleDuctInletSideMixer": "air_terminals",
    "IB_AirTerminalSingleDuctParallelPIUReheat": "air_terminals",
    "IB_AirTerminalSingleDuctSeriesPIUReheat": "air_terminals",
    "IB_AirTerminalSingleDuctVAVHeatAndCoolNoReheat": "air_terminals",
    "IB_AirTerminalSingleDuctVAVHeatAndCoolReheat": "air_terminals",
    "IB_AirTerminalSingleDuctVAVNoReheat": "air_terminals",
    "IB_AirTerminalSingleDuctVAVReheat": "air_terminals",
    "IB_BoilerHotWater": "plant_components",
    "IB_FanConstantVolume": "terminal_components",
    "IB_FanVariableVolume": "terminal_components",
    "IB_FanOnOff": "terminal_components",
    "IB_CoilHeatingElectric": "terminal_components",
    "IB_CoilHeatingDXSingleSpeed": "terminal_components",
    "IB_CoilCoolingDXSingleSpeed": "terminal_components",
    "IB_CoilCoolingDXVariableRefrigerantFlow": "terminal_components",
    "IB_CoilHeatingDXVariableRefrigerantFlow": "terminal_components",
    "IB_CoilCoolingCooledBeam": "terminal_components",
    "IB_CoilCoolingFourPipeBeam": "terminal_components",
    "IB_CoilHeatingFourPipeBeam": "terminal_components",
    "IB_CoilCoolingWater": "terminal_components",
    "IB_CoilHeatingWater": "terminal_components",
    "IB_CoilHeatingWaterBaseboardRadiant": "terminal_components",
    "IB_ChillerElectricEIR": "plant_components",
    "IB_CoolingTowerVariableSpeed": "plant_components",
    "IB_HeatExchangerFluidToFluid": "plant_components",
    "IB_AirConditionerVariableRefrigerantFlow": "vrf",
    "IB_ZoneHVACPackagedTerminalAirConditioner": "terminal_zone_equipment",
    "IB_ZoneHVACPackagedTerminalHeatPump": "terminal_zone_equipment",
    "IB_ZoneHVACFourPipeFanCoil": "terminal_zone_equipment",
    "IB_ZoneHVACTerminalUnitVariableRefrigerantFlow": (
        "terminal_zone_equipment"
    ),
    "IB_ZoneHVACBaseboardRadiantConvectiveWater": "terminal_zone_equipment",
    "IB_ZoneHVACUnitHeater": "terminal_zone_equipment",
    "IB_ZoneHVACUnitVentilator_CoolingHeating": "terminal_zone_equipment",
    "IB_ZoneHVACUnitVentilator_CoolingOnly": "terminal_zone_equipment",
    "IB_ZoneHVACUnitVentilator_HeatingOnly": "terminal_zone_equipment",
    "IB_PlantLoop": "plant_loops",
    "IB_PlantLoopBranches": "plant_components",
    "IB_PumpConstantSpeed": "plant_components",
    "IB_PumpVariableSpeed": "plant_components",
    "IB_DistrictCooling": "plant_components",
    "IB_DistrictHeatingWater": "plant_components",
    "IB_SetpointManagerScheduled": "plant_components",
    "IB_SetpointManagerColdest": "setpoint_managers",
    "IB_SetpointManagerFollowGroundTemperature": "setpoint_managers",
    "IB_SetpointManagerFollowOutdoorAirTemperature": "setpoint_managers",
    "IB_SetpointManagerFollowSystemNodeTemperature": "setpoint_managers",
    "IB_SetpointManagerMixedAir": "setpoint_managers",
    "IB_SetpointManagerMultiZoneCoolingAverage": "setpoint_managers",
    "IB_SetpointManagerMultiZoneHeatingAverage": "setpoint_managers",
    "IB_SetpointManagerMultiZoneHumidityMaximum": "setpoint_managers",
    "IB_SetpointManagerMultiZoneHumidityMinimum": "setpoint_managers",
    "IB_SetpointManagerMultiZoneMaximumHumidityAverage": "setpoint_managers",
    "IB_SetpointManagerMultiZoneMinimumHumidityAverage": "setpoint_managers",
    "IB_SetpointManagerOutdoorAirPretreat": "setpoint_managers",
    "IB_SetpointManagerOutdoorAirReset": "setpoint_managers",
    "IB_SetpointManagerScheduledDualSetpoint": "setpoint_managers",
    "IB_SetpointManagerSingleZoneCooling": "setpoint_managers",
    "IB_SetpointManagerSingleZoneHeating": "setpoint_managers",
    "IB_SetpointManagerSingleZoneHumidityMaximum": "setpoint_managers",
    "IB_SetpointManagerSingleZoneHumidityMinimum": "setpoint_managers",
    "IB_SetpointManagerSingleZoneReheat": "setpoint_managers",
    "IB_SetpointManagerSystemNodeResetHumidity": "setpoint_managers",
    "IB_SetpointManagerSystemNodeResetTemperature": "setpoint_managers",
    "IB_SetpointManagerWarmest": "setpoint_managers",
    "IB_SetpointManagerWarmestTemperatureFlow": "setpoint_managers",
}
